### ISSUE TITLE
Assignment 5 is ready for grading

### ISSUE THREAD

**Issue by alex-cox-gsd** [SES-5215-F2020/alexcox-quant#5]
Hello! My assignment 5 submission is ready for grading, you can find the HTML here: https://ses-5215-f2020.github.io/alexcox-quant/Assignment_5_Quant.html

**Comment by saratepfer** [comment]
nice job, Alex!

- note that when you log transform PINCP, you need to first filter out the zero values, otherwise R will produce NaNs (not a number)
- It would be great to see some interpretation of the last graph you produced. What does this graph tell you about the interaction you tested?
